### DISCUSSION TITLE
Having trouble with the hass.services.call function on pyscript

### DISCUSSION THREAD

**Discussion by zroger49** [custom-components/pyscript#224] [Q&A] [answered]
Greetings! :) 
Currently working on simple automation that updates the options of a my input_selector entity. 

My automation looks like this: 
```
automation: 
   - alias: "New wallpaper update"
    trigger:
      platform: event
      event_type: folder_watcher
      event_data:
        event_type: created
    action:
      service: pyscript.update_wallpaper_options
      data_template: 
        action: 'Add'
        entity_id: input_select.wallpaper_selector
        file: "{{ trigger.event.data.path }}"
```

While the pyscript service looks like this: 

```
def update_wallpaper_options(action = None, entity_id = None, file = None):
    """Updates the list of wallpaper options each time a new file is added to the folder"""
    if file != None:
        file = file.split('/')[-1] #Get the file name (change background image already point to the correct path) 
        current_options = hass.states.get(entity_id).attributes['options'] #get the current options 
        if action == 'Add': 
            current_options.append(file) #Append the file name to the current options 
            service_data = {'entity_id' : entity_id, 'options': current_options}
            hass.services.call('input_select', 'set_options', service_data) #call the service to update the options of the entity 
```

From testing I know for a fact the last line is what is crashing home assistant 

Additional information: 
I'm using homekit-infused dashboard, which I have integrated using a package

My input_select config looks like this: 

```
  wallpaper_selector: 
    name: Wallpaper selector 
    options: 
      - Theme Wallpaper

```

Any help would be appreciated
