### DISCUSSION TITLE
How to create and reload an app

### DISCUSSION THREAD

**Discussion by Robert1991** [custom-components/pyscript#229] [Q&A] [answered]
Hi Guys, im struggling with defining an app in pyscript. I tried both ways, having the app in a single file beneath apps and having the app in a folder containig also the __init__.py file, the app is also defined in my config.yaml . None of the described ways seems to work, the app is not found on pyscript.reload or HA new start.

Am I missing something?

```
pyscript:
  allow_all_imports: true
  hass_is_global: true
  apps:
    home_server_update:
      # 123
      - update_log: "test"
```
Debug log says:

```
[custom_components.pyscript] load_scripts: skipping /config/pyscript/apps/home_server_update.py (app_name=home_server_update) because config not present
```

thanks!
