### DISCUSSION TITLE
OttoScript v0.2!

### DISCUSSION THREAD

**Discussion by qui3xote** [custom-components/pyscript#299] [Show and tell]
Made a big leap forward on OttoScript over the weekend and have moved more of my automations over.  I've added case statements and now support nested logic and variables! As before, would love input/feedback. 
https://github.com/qui3xote/ottoscript/releases/tag/v0.2
https://github.com/qui3xote/ottopyscript/releases/tag/0.1.1

Here's an OttoScript that I use to control my office setup, based on an input boolean. 

```
WHEN input_boolean.working CHANGES
  CASE
    IF input_boolean.working == 'on'
        TURN ON light.cupola_lights
        CALL switch.turn_on ON switch.noise_machine_on_off
        CALL automation.trigger ON automation.working_lights
    END
    IF input_boolean.working == 'off'
        TURN OFF light.cupola_lights
        TURN OFF switch.noise_machine_on_off
    END
  END;
```

For comparison, here's the (mostly) same automation in YAML:
```
alias: Working Start
description: ''
trigger:
  - platform: state
    entity_id: input_boolean.working
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_boolean.working
            state: 'off'
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.noise_machine_on_off
    default:
      - service: switch.turn_on
        target:
          entity_id: switch.noise_machine_on_off
      - service: automation.trigger
        target:
          entity_id: automation.new_automation
mode: single
```
