### DISCUSSION TITLE
call.service - syntax clarification

### DISCUSSION THREAD

**Discussion by mjhcdk** [custom-components/pyscript#302] [Q&A] [answered]
Properly a simple question , but I am not able to figure out via documentation.

I try to call some services that have some subsections like target: but not able to figure out the syntax. 
I have tried below, but gives an error 
```
eufy_security.alarm_arm_custom1(target={entity_id="alarm_control_panel.d35"})

022-01-16 12:28:49 ERROR (MainThread) [custom_components.pyscript.file.cameramode] Exception in </config/pyscript/cameramode.py> line 69:
          eufy_security.alarm_arm_custom1(target={entity_id="alarm_control_panel.d35"})
                                                           ^
SyntaxError: invalid syntax (cameramode.py, line 69)

```
within HA develop the call looks like this 

```
  service: eufy_security.alarm_arm_custom2
  data: {}
  target:
    entity_id: alarm_control_panel.d35

```

**Comment by craigbarratt** [comment]
It's likely needs to be a dict, so something like:
```
eufy_security.alarm_arm_custom1(target={"entity_id": "alarm_control_panel.d35"})
```

**Reply by mjhcdk** [reply]
Thx for promptly feedback, but I still got error when call service 

```
2022-01-16 12:46:33 INFO (MainThread) [custom_components.pyscript.global_ctx] Reloaded /config/pyscript/cameramode.py
2022-01-16 12:46:40 ERROR (MainThread) [custom_components.pyscript.file.cameramode.cam_setmode] Exception in <file.cameramode.cam_setmode> line 74:
          eufy_security.alarm_arm_custom2(target={"entity_id": "alarm_control_panel.d35"})
                                                  ^
MultipleInvalid: extra keys not allowed @ data['target']
```

**Reply by mjhcdk** [reply]
Btw. This HA script I try to migrate

```
eufy_camera_have:
  alias: Eufy Camera Have
  sequence:
  - service: eufy_security.alarm_arm_custom1
    target:
      entity_id: alarm_control_panel.d35
  mode: single
  icon: mdi:cctv
```
