### DISCUSSION TITLE
pyscript in templates

### DISCUSSION THREAD

**Discussion by 2Max2Pax** [custom-components/pyscript#309] [Q&A] [answered]
I would like using a pyscript function in an automation/script of Home assistant like a template.
for example:
pyscript funtion:
```
@service
def my_function(x):
  return x+1
````
HA Script:
```
alias: templating_pyscript
sequence:
  - service: notify.persistent_notification
    data:
      message: '{{ pyscript.my_function(1) }}'
mode: single
```
and return 2
Is there a way to make it work?
