### DISCUSSION TITLE
Shouldn't swtch.toggle() on a group toggle the whole group to one state?

### DISCUSSION THREAD

**Discussion by wsw70** [custom-components/pyscript#381] [Q&A]
Consider the group

```yaml
salon_milieu:
    name: salon milieu
    entities:
      - switch.salon_blanche_entree_gauche
      - switch.salon_tableau
      - switch.salon_lampe_haute
```

If I switch on (through the UI for instance), say, `switch.salon_tableau`, and call in my script `switch.toggle(entity_id="group.salon_milieu")`, each entity of the group is toggled **individually**. 

This means in the case above that I will alternate between 1 or 2 lamps switched on/off as I call `switch.toggle(entity_id="group.salon_milieu")`.

I was expecting a toggle on a group to work similarly to 

![image](https://user-images.githubusercontent.com/1345886/183310012-a10f5d5c-64b4-4681-b442-fb160b23f13a.png)

but apparently, I was wrong.

I can write a smarter toggle function, I just wanted to make sure it is not a terrible misunderstanding :)
