### DISCUSSION TITLE
calling service, multiple items for "content"?

### DISCUSSION THREAD

**Discussion by sn00zerman** [custom-components/pyscript#401] [Q&A] [answered]
Hi all,

I’m currently busy with a home-build automation in PyScript.
I can call services, but I don’t know how to pass mutliple lines for “content”.

**This is my service call:**

```
service: browser_mod.popup
data:
  type: custom:popup-card
  title: Tuin - Hoeklamp
  size: wide
  content:
    type: iframe
    url: http://192.168.123.88:8123/local/scenedefinitions/overview.html

```
**To do this in pyscript, I use:**
`service.call('browser_mod','popup',blocking=True,type='custom:popup-card',title='bla bla bla',size='wide', ...)`

With what do I need to replace the 3 dots, to be able to pass the type & url to this service-call ?

Desparately seeking help :frowning:

best regards,
Kris
