### DISCUSSION TITLE
Scripts run, but doc_strings and autoreload don't work

### DISCUSSION THREAD

**Discussion by twastvedt** [custom-components/pyscript#407] [Q&A]
Hi! I have pyscript 1.3.3 installed through HACS on Home Assistant 2022.7.7, which is running in a Docker container on a Rock64 board (similar to Raspberry Pi). I can call scripts through the Services page, but autoreloading doesn't work (I have to call the pyscript.reload service) and the doc_string is not read (or, at least, nothing from it affects the Services page). I put this in my configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.pyscript.file: debug
```
but I don't see any pyscript logs except for output from `log.info` calls in my functions. Any thoughts on where to start in debugging this? Thanks!
