### DISCUSSION TITLE
how to convert this yaml service call?

### DISCUSSION THREAD

**Discussion by phsdv** [custom-components/pyscript#534] [Q&A] [answered]
It is more a yaml question than pyscript :-) How would you convert this yaml service call to pyscript?
```
  - service: tesla_custom.api
    data:
      command: CHARGING_AMPS
      parameters:
        path_vars:
          vehicle_id: '{{ state_attr(''binary_sensor.carname_online_sensor'', ''id'') }}'
        charging_amps: '16'
```
The syntax is: service.call(domain, name, **kwargs)
But I don´t understand yaml good enough. The domain is, I think, tesla_custom.api, but then I am lost
