### DISCUSSION TITLE
passing output to use in other scripts with response_variable

### DISCUSSION THREAD

**Discussion by lawya-cm** [custom-components/pyscript#541] [Q&A]
Is there a way to call a pyscript from within some other automation or yaml script and make use of the output in that other script. 

For many services you can use `response_variable` e.g

  ```
- service: weather.get_forecast
    data:
      type: hourly
    target:
      entity_id: weather.forecast_home
    response_variable: hourly_forecast
```

Is this possible in a pyscript or is there another approach other than using a helper with an input_text as I am doing now?
