### DISCUSSION TITLE
Service Notify Mobile Actions: What is the data structure?

### DISCUSSION THREAD

**Discussion by ALEXTHENINJA007** [custom-components/pyscript#602] [Q&A] [answered]
Im trying to write a script to send Push Notifications to mobile but I can figure out the data structure required for actions within the push notification. 

So the yaml specs look like this
```
service: notify.mobile_XXXXXXX
data:
  message: "Something happened at home!"
  data:
    actions:
      - action: "ALARM" # The key you are sending for the event
        title: "Sound Alarm" # The button title
 ```

and I have tried stuff like this but I cant seem to get it to work. 
```
notify.mobile_XXXXXXXX(message="actiontest",data={actions: [{"action": "Test","title": "sometitle"}]})
notify.mobile_XXXXXXXX(message=todoItem.summary,actions={{"action": "ACTION", "title": "Complete"},{"action": "action2", "title": "Sleep"}})
```

If anyone knows what the structure is I need that would be much appreciated thankyou.
