### DISCUSSION TITLE
Creating configuration.yaml custom template sensor entities using pyscript

### DISCUSSION THREAD

**Discussion by dinki** [custom-components/pyscript#606] [Q&A]
In this [response](https://github.com/custom-components/pyscript/discussions/278#discussioncomment-1709773) @dlashua mentioned creating configuration.yaml code:

> Have your pyscript code actually create configuration.yaml for these groups and then call the reload service after an update. If you go this route, you probably want to split the pyscript generated groups into their own config file and add the proper YAML in configuration.yaml to read from that file so you don't have to deal with overwriting manually defined groups and config. You also need to make sure you don't call reload until all group changes are made. Which means you'll need one pyscript to handle all the groups, or you'll have to get really clever with how you link it all together.

Is it possible that someone could share code on how to do this?   I am working on a project that requires the user to set up custom template sensor devices for use with the project.  I am trying to find an easy way for the user to create these versus manually creating each entry.  This would save both them and me headache as I am aiming to make this available to even folks on the entry level of Home Assistant.

An example of what this device config looks like:

```
template:
  - sensor:
    - name: AssistSat_ViewLR
      state: ""
      attributes:
        type: view_audio
        mode: "normal"
        mic_device: "sensor.firehd_7_stt"
        mediaplayer_device: "media_player.tabletfullkiosk"
        display_device: "sensor.thinksmart_lr_browser_path"
        view_timeout: "20"
        title: ""
        message: ""
        message_font_size: "3vw"
        image: ""
        timer: ""
        alarm: ""
        cycle_view: ""
        do_not_disturb: false
```

These would need user input but the rest are just placeholders:

```
        type: view_audio
        mic_device: "sensor.firehd_7_stt"
        mediaplayer_device: "media_player.tabletfullkiosk"
        display_device: "sensor.thinksmart_lr_browser_path"
```

These devices are really just data stores of information that are used in the project for each Assist satellite to determine its output parts, modes, controls and data to present to the user when needed.

Any advice or help in generating the YAML necessary would be a plus.  Thanks
