### DISCUSSION TITLE
Send secret into script (not application)

### DISCUSSION THREAD

**Discussion by Nikolay-Ch** [custom-components/pyscript#661] [Q&A]
Hi,
How I can send some secret from secrets.yaml into script (not application)?
In documentation I found this:
```
pyscript:
  allow_all_imports: true
  apps:
    service_checker:
      - service_name: my_service
        url: !secret my_secret_url
        api_key: !secret my_secret_api_key
```
But for single script this solution not worked.

**Comment by ALERTua** [comment]
`secrets.yaml`:
```yaml
secret1: "this is a secret!"
```

pyscript `config.yaml`
```yaml
allow_all_imports: true
hass_is_global: true

secrets:
  secret1: !secret secret1
```

a separate pyscript `secrets.py`, if you want
```python
def SECRET(value):
    # noinspection PyUnresolvedReferences
    return pyscript.config.get('secrets', {}).get(value)

# and if you want
SECRET_1 = SECRET('secret1')
```

pyscript `script.py`
```python
from secrets import SECRET_1
# or
from secrets import SECRET
SECRET_1 = SECRET('secret1')
#or just
SECRET_1 = pyscript.config.get('secrets', {}).get('secret')
```
