### DISCUSSION TITLE
How to react to button click from Zigbee2Mqtt?

### DISCUSSION THREAD

**Discussion by Hugo-Persson** [custom-components/pyscript#695] [Q&A]
Hi!

I have the following trigger that I want to convert to pyscript
```yaml
triggers:
  - domain: mqtt
    device_id: 899f934be2d6efe426afead053e9532d
    type: action
    subtype: "off"
    discovery_id: 0x8cf681fffe2edc75 action_off
    id: "off"
    trigger: device
  - domain: mqtt
    device_id: 899f934be2d6efe426afead053e9532d
    type: action
    subtype: "on"
    discovery_id: 0x8cf681fffe2edc75 action_on
    id: "on"
    trigger: device
```

How would I do this? Any help would be appreciated
