### ISSUE TITLE
Question: how to organize code in the case of private and shared apps?

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#134]
https://hacs-pyscript.readthedocs.io/en/stable/reference.html#configuration explains how to structure code and which directories are automatically loaded. 

My usecase is the following (today everything is under `<config>/pyscript/`):
- monitoring apps which I call `dash__app1.py`, `dash__app2.py` etc.
- automation apps which I call `automation__app1.py`, etc.

All the apps are independent, and only "grouped" together in these two groups.

The relevant `configuration.yaml` entries are

```
pyscript:
  allow_all_imports: true
  hass_is_global: true
  zigbee:
    light:
      salon_interrupteur_canape:
        single:
          - group.salon,off
          - group.salon_avant,toggle
        double:
          - group.salon,toggle
      salon_interrupteur_mur:
        single:
          - group.salon,toggle
        double:
          - group.michael,off
          - group.martin,off
          - group.parents,off
        hold:
          - group.salon_avant,toggle
     (...)
  rf433:
    light:
      9415E1:
        single:
          - switch.martin_entree,toggle
      9415E4:
        single:
          - switch.martin_pixar,toggle
      (...)
  meross:
    - name: meross01
      id: 2006176333738751801348e1e91fb91a
      channels: 1
      model: mss110
    - name: meross02
      id: 2005281078830290814148e1e91d807b
      channels: 6
    (...)
```

They are accessed by the apps via for instance `pyscript.config['meross']` (a `list` in that case).

I keep a git repo for all my HA configuration, that includes `pyscript`.

I now have an extraordinary, groundbreaking app which I would like to share with the world :) - and this is an opportunity to redesign my directory structure.

First, my understanding is that the configuration variables discussed in the docs 

```
pyscript:
  allow_all_imports: true
  apps:
     my_app1:
        # any settings for my_app1 go here
        hello: world
     my_app2:
        # any settings for my_app2 go here
        wazii: wazaa
```
are accessed as follows: `pyscript.config['apps']['my_app1']['hello']`. In other words, there is no link between the place a script is in the directories with its ability to reach for configuration variables (it cal get everything, even from other apps). This is OK, I just wanted to make sure.

So back to what I would like to have, I am divided between two approaches:

## approach 1

- `<config>/pyscript/scripts/dash/(all the dash apps together)`
- `<config>/pyscript/scripts/automation/(all the automation apps together)`
- `<config>/pyscript/scripts/automation/genius_app/genius_app.py`

`genius_app` is the one I would like to distribute, through a git repository in that directory that I would push to GitHub.

## approach 2

Similar to the approach one, except that I would have all the apps in `<config>/pyscript/apps/[dash|automation]/app_name/__init__.py`

I have a hard time understanding the actual differences between these approaches, except that the second one has more boilerplate (and non-distinctive names for the apps (namely `__init__.py`))

Is this just a matter of simplifying the distribution? (in approach 2 all the apps are truly separated). What disturbs me in the second case is really the non-distinctive name.

**EDIT**: ah, I see that my solution nr 2 will not work, there can be only one subdirectory under `apps`. So no `<config>/pyscript/apps/dash/someapp/__init__.py`
