### ISSUE TITLE
Pyscript service parameter cache issue?

### ISSUE THREAD

**Issue by Tolriq** [custom-components/pyscript#159]
Hi,

I'm trying to use pyscript to see if it can fit my needs but I'm facing a strange issue during tests that I can't explain.

HA 2020.2.3 / pyscript 1.2.1

Give the simple python : 
```
@service
def hello_world(action=None, id=None):
    """hello_world example using pyscript."""
    log.warning(f"hello world: got action {action} id {id}")      
```

I call it from a simple HA script:
```
alias: Tst
sequence:
  - service: pyscript.hello_world
    data:
      action: z
      id: z
mode: single
```

After a fresh start I call the script with 2 parameters z / z it will properly work and log z / z
I edit the HA script and change the parameter to a /a then run it, it will properly work and log a / a
Then any other edit of the parameter to any new value will always log a / a and no more take in account the new values.

Don't know if it's an HA or pyscript issue and where to start looking at.
