### ISSUE TITLE
Calling services with nested parameters

### ISSUE THREAD

**Issue by watermarkhu** [custom-components/pyscript#200]
It seems that nested service call parameters are not supported, e.g. with [actionable notifications](https://companion.home-assistant.io/docs/notifications/actionable-notifications/#building-actionable-notifications): 

```yaml
service: notify.mobile_app_<your_device_id_here>
data:
  message: "Something happened at home!"
  data:
    actions:
      - action: "ALARM" # The key you are sending for the event
        title: "Sound Alarm" # The button title
      - action: "URI" # Must be set to URI if you plan to use a URI
        title: "Open Url"
        uri: "https://google.com" # URL to open when action is selected, can also be a lovelace view/dashboard      
```
It would seem logical if of the parameter `actions` a dictionary or list may be passed to support such parameters, such that the above service call in pyscript would be:
```python
notify.mobile_app(
   message = "Something happened at home!",
   actions = [
      {'action': 'ALARM', 'title': 'Sound Alarm'},
      {'action': 'URI', 'title': 'Open Url', 'uri': 'https://google.com'},
   ]
)
```

However, this currently returns the error `^ MultipleInvalid: extra keys not allowed @ data['actions']`
