### ISSUE TITLE
Can't figure out how to access pyscript.app_config

### ISSUE THREAD

**Issue by fovea1959** [custom-components/pyscript#313]
I have this script:

```
import pyscript

@state_trigger('switch.sonoff_s31_9e8c80', state_check_now=True, kwargs={'a': 'sonoff'})
def openweathermap_updated(**kwargs):
    log.info(f'got arguments {kwargs}')
    try:
        log.info(f'... and {pyscript.app_config}')
    except Exception as error:
        log.error(f'wth, can\'t get app_config: {error}')
```

and this configuration:

```
apps:
  openweather_update:
    wleds:
      - a
      - b
    tasmotas:
      - c
      - d
```

I keep getting this:

```
2022-02-03 23:40:20 INFO (MainThread) [custom_components.pyscript.file.openweathermap_update.openweathermap_updated] got arguments {'trigger_type': 'state', 'var_name': 'switch.sonoff_s31_9e8c80', 'value': 'on', 'old_value': 'off', 'context': Context(user_id=None, parent_id=None, id='0ad6760f6b02e79356340644eb3501f1'), 'a': 'sonoff'}
2022-02-03 23:40:20 ERROR (MainThread) [custom_components.pyscript.file.openweathermap_update.openweathermap_updated] wth, can't get app_config: module 'pyscript' has no attribute 'app_config'
```

I don't understand why I can't access the app_config; what am I doing wrong?

**Comment by craigbarratt** [comment]
First, don't import pyscript.

Second, what is the path of your test script?  It needs to be something like pyscript/apps/openweather_update.py.  The error message suggests it's just a regular script in pyscript/openweather_update.py, which can't access app config.

Third, is that yaml fragment you included inside pyscript, ie:
```yaml
pyscript:
  apps:
    openweather_update:
      wleds:
        - a
        - b
      tasmotas:
        - c
        - d
 ```
See the [docs.](https://hacs-pyscript.readthedocs.io/en/stable/reference.html#accessing-yaml-configuration).
