### ISSUE TITLE
JupyterLabs Addon

### ISSUE THREAD

**Issue by chancancode** [custom-components/pyscript#317]
Hey there, thank you for working on this add-on, I really enjoying working on automations using this platform.

Just wanted to put it out there that I managed to get the [JupyterLab](https://github.com/hassio-addons/addon-jupyterlab) add-on to work with the pyscript kernel, which is really nice because:

1. I don't have to setup a python environment and jupyter on my personal computer
2. I don't have to setup a long-lived access token
3. it works from anywhere
4. it shows up inside the Home Assistant UI

<img width="1568" alt="Screen Shot 2022-02-11 at 8 33 54 AM" src="https://user-images.githubusercontent.com/55829/153630715-c6453386-d748-465e-82ea-54efe17468d1.png">

I suspect this may be an easier setup for most new users as well, so maybe we should consider promoting this method instead of the local jupyter setup?

Here is my config for my JupyterLab add-on:

```yaml
github_access_token: ''
system_packages: []
init_commands:
  - pip install hass_pyscript_kernel
  - jupyter pyscript install
  - echo "[homeassistant]" > /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
  # change this to your HA host's IP, see below
  - echo "hass_host = 1.2.3.4" >> /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
  - echo "hass_url = http://supervisor/core/" >> /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
  - echo "hass_token = $SUPERVISOR_TOKEN" >> /usr/local/share/jupyter/kernels/pyscript/pyscript.conf
```

And here is how/why (I think) it works.

When the JupyterLab add-on starts, it will run whatever list of commands in `init_commands`, which gives us the opportunity to install the pyscript kernel. We are basically just running the same commands as the current instructions here.

It's a bit inefficient to do this every time the add-on starts up as opposed to baking it into the Docker image, but it doesn't appear to take very long, though maybe we should check with the maintainers of the add-on to see if this is something they would be open to adding, I don't think it really harms anything to have the kernel installed even if you are not using pyscript? (Well, other than it will show up on the list of kernel selectors and the launcher screen, which is perhaps going to be confusing for some?)

As for configuring the pyscript kernel, since we are running inside an add-on (which has [access to the API](https://github.com/hassio-addons/addon-jupyterlab/blob/ef5a3d3769cc846d38ab415afa382abef912d74d/jupyterlab/config.yaml#L12)), we can go through the [API proxy](https://developers.home-assistant.io/docs/add-ons/communication#home-assistant-core) and using the injected `SUPERVISOR_TOKEN` rather than a long-lived access token.

On the other hand, it seems like I did have to set `hass_host` to the "real" IP of the Home Assistant host on the actual host network (something like `10.0.0.2`). I thought I could maybe get away with using `supervisor` (the hostname in `/etc/host) or something like `172.30.32.1` (not sure if this is documented/officially supported, but this seems to be the actual Home Assistant core on the docker network), but no dice.

It doesn't bother me a whole lot, but it would be nice if we can find a solution that is a bit more resilient here. Perhaps it has something to do with how the pyscript kernel service listens/binds to the ports, maybe it is only binding to the public interface?

In any case, I am not sure what the `hass_host` configuration is for and why it is needed, since we already have access to the API. I suppose we need to open a direct connection to do things that you can't do over the API, which is fine, but instead of requiring the user to set this, couldn't the kernel code on the pyscript side detect what its own address is, the port number it opened, etc, and "publish" that as a state variable like `pyscript.kernel_address` and `pyscript.kernel_port`, which can then be read from the API? Anyway this is getting into territories I am not very familiar with as I am not a python programmer, someone more familiar with the code can chime in.

Other than that relatively minor detail, everything appears to work nicely and so far I haven't encountered any issues yet.
