### ISSUE TITLE
problems with number sliders

### ISSUE THREAD

**Issue by SiriosDev** [custom-components/pyscript#437]
number selector slider declared in triple quotes for services made with pyscript have this problem:

https://user-images.githubusercontent.com/26876994/220390388-c78a501a-4194-4fd7-8b26-9b8a92fabfe0.mp4

here the part of yaml about the problem:
```yaml
position:
    name: Position
    description: Select a Mode (0%-100%) (required for "setPosition" command)
    example: 50
    default: 50
    required: false
    selector:
      number:
        min: 0
        max: 100
        step: 1
        unit_of_measurement: "%"
        mode: slider
```
