### ISSUE TITLE
pyscript.app_config

### ISSUE THREAD

**Issue by marshalltech81** [custom-components/pyscript#518]
In following the documentation, https://hacs-pyscript.readthedocs.io/en/latest/reference.html#configuration, I tried "To use the UI, go to the Configuration -> Integrations page and select “+” to add `Pyscript Python scripting.`".  However I could not find that option any where in the UI. 

So in my configuration.yaml, I did the manual option of specifying:
```
pyscript: !include pyscript/config.yaml
```

And in my pyscript/config.yaml:
```
allow_all_imports: true
apps:
  my_app1:
    # any settings for my_app1 go here
  my_app2:
    # any settings for my_app2 go here
```

Lastly in my script for `my_app1` as an example, I am trying to call `log.info(f"configuration {pyscript.app_config}")` and the error I keep getting back is:
```
NameError: name 'pyscript.app_config' is not defined.
```

Any thoughts?

Thank you in advance!
