### ISSUE TITLE
Logging Documentation for Apps vs Scripts

### ISSUE THREAD

**Issue by marshalltech81** [custom-components/pyscript#520]
In following https://hacs-pyscript.readthedocs.io/en/latest/reference.html, it is not readily apparent that the steps for setting logging on a script by script basis like illustrated here:

```
logger:
  default: info
  logs:
    custom_components.pyscript.file: info
    custom_components.pyscript.file.my_script.my_function: debug
```

would change if the script in question is really an app which appears to change these directions to:
```
logger:
  default: info
  logs:
    custom_components.pyscript.apps: info
    custom_components.pyscript.apps.my_script.my_function: debug
```

I was able to finally piece this together based on the output of the debugging log when I got this working using `logger.set_level(**{"custom_components.pyscript": "debug"})` at the top of my script/app just to see how the debugging log would come through.
