### ISSUE TITLE
Excluding Pyscript from Logbook HA

### ISSUE THREAD

**Issue by RamiRihawi** [custom-components/pyscript#613]
Anyway to exclude the pyscript logs from Recorder and logbook in home assistant?
every 10 second and new execution is registered and this will flood the database.
![Pyscript](https://github.com/custom-components/pyscript/assets/18113211/cb0d9c1d-5fd4-4e3c-867d-a84c1d756929)

**Comment by ALERTua** [comment]
have you tried 
```yaml
logbook:
  exclude:
    domains:
      - pyscript

recorder:
  exclude:
    domains:
      - pyscript
```
?
