### ISSUE TITLE
Calling service on device picks up the wrong device ID

### ISSUE THREAD

**Issue by TheSimpleZ** [custom-components/pyscript#681]
I am trying to call a service to start my dishwasher.

The service YAML that works:
```yaml
action: connectlife.set_action
target:
  device_id: f843d2956a8f5543756e46bfbacd84e7
data:
  action: "2"
```

This is what I write in pyscript:
```python
connectlife.set_action(device_id="f843d2956a8f5543756e46bfbacd84e7", action="2")
```

But for some reason, this fails. In the logs I see:
```
2025-01-14 02:18:02.148 DEBUG (MainThread) [custom_components.connectlife.services] device_id: 0000000000007395170001202200024030030
2025-01-14 02:18:02.148 DEBUG (MainThread) [custom_components.connectlife.services] Setting Actions to 2 on 0000000000007395170001202200024030030
```

I have no idea where that device ID in the logs comes from. What am I missing here?
