### ISSUE TITLE
Feature Request: MQTT trigger

### ISSUE THREAD

**Issue by wsw70** [custom-components/pyscript#98]
**Note: the original tile of the question was "[question] how to run a always-on script?"**

I am converting my automation from AppDaemon to `pyscript` and some of them depend on MQTT (as a client). A typical case is a switch emitting to MQTT topic I want to listen to and act accordingly.

This means that such a script is not triggered by anything but runs in the background, responds to some events it manages itself (MQTT messages in my case), and then contacts HA for some actions (switching on a light for instance).

**Is it possible to run such a script?** The only cases I saw in the documentation are ones that react to something (either time based, or coming from HA)

One solution would be to use HA to manage the MQTT messages, but there are problems with this in some cases (see https://community.home-assistant.io/t/how-to-get-the-name-of-the-actual-state-topic-in-an-mqtt-sensor/248541 for an example). Using HA is doable but I would prefer to avoid automations there and move everything to pyscript for consistency.

**Comment by dlashua** [comment]
You can use a `@time_trigger` of `startup` to indicate that the script should run immediately. Then, as long as the logic inside of that script never stops, it will continue to run.

However, if you set up a Home Assistant automation that subscribes to the topic and then fires an event with the topic and payload in it, you can easily use `@event_trigger` to process these and don't need the script to be running "all the time".

Something like:

```yaml
- alias: MQTT Messages
  trigger:
    - platform: mqtt
      topic: mytopic/#
  action:
    - event: MQTT_MESSAGE
      event_data:
        topic: "{{ trigger.topic }}"
        payload: "{{ trigger.payload }}"
```

```python
@event_trigger('MQTT_MESSAGE')
def mqtt_message(**data):
  log.info(f"Got an MQTT MESSAGE: {data}")
```
